name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.5
    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework-seleniumlibrary
    - name: Install Allure Command Line
      run: |
        wget -q -O - https://dl.bintray.com/qameta/generic/install.sh | bash && \
        sudo mv /usr/local/bin/allure /usr/bin
    - name: Run E2E Tests
      run: robot --listener allure_robotframework -d ./logs -v BROWSER:chrome tests
    - name: Generate Allure Report
      run: allure generate output/allure -o output/allure-report --clean
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: Allure Report
        path: output/allure-report
  edge:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.5
    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotframework-seleniumlibrary
    - name: Install Allure Command Line
      run: |
        wget -q -O - https://dl.bintray.com/qameta/generic/install.sh | bash && \
        sudo mv /usr/local/bin/allure /usr/bin
    - name: Run E2E Tests
      run: robot --listener allure_robotframework -d ./logs -v BROWSER:edge tests
    - name: Generate Allure Report
      run: allure generate output/allure -o output/allure-report --clean
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: Allure Report
        path: output/allure-report