name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  chrome:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.5

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt 
        pip install robotframework-seleniumlibrary

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:chrome tests 

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.ROBOT_REPORTER_TOKEN }}
        report_path: logs

    - name: Upload Reporter
      uses: actions/upload-artifact@v4.3.1
      if: always()
      with:
        name: Chrome Tests Report
        path: logs


  firefox:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v4.1.5

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt 
        pip install robotframework-seleniumlibrary

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:electron tests 

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.ROBOT_REPORTER_TOKEN }}
        report_path: logs

    - name: Upload Reporter
      uses: actions/upload-artifact@v4.3.1
      if: always()
      with:
        name: Electronx Tests Report
        path: logs        